# Generated by Django 5.1 on 2024-09-05 14:47

import django.db.models.deletion
import eLearning_api.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPost',
            new_name='UserStatus',
        ),
        migrations.RenameField(
            model_name='userstatus',
            old_name='post_id',
            new_name='user_status_id',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(blank=True)),
                ('status', models.IntegerField(choices=[(0, 'undefined'), (10, 'Active'), (50, 'Archived')], default=eLearning_api.utils.Status['Active'])),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateTimeField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('course_material_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'undefined'), (10, 'Active'), (50, 'Archived')], default=eLearning_api.utils.Status['Active'])),
                ('type', models.IntegerField(choices=[(0, 'undefined'), (10, 'Image'), (20, 'Pdf'), (30, 'Word'), (40, 'Excel'), (50, 'Csv')], default=eLearning_api.utils.Status['Active'])),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
