# Generated by Django 5.1 on 2024-09-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning_api', '0002_rename_userpost_userstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
