# Generated by Django 5.1 on 2024-09-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning_api', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='created_by_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
