# Generated by Django 5.1 on 2024-09-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning_api', '0004_userstatus_created_by_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
