# Generated by Django 5.1 on 2024-09-05 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning_api', '0007_remove_coursematerial_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eLearning_api.course'),
            preserve_default=False,
        ),
    ]
