# Generated by Django 5.1 on 2024-09-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning_api', '0008_coursematerial_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='file_name',
            field=models.FileField(blank=True, upload_to='images/course/material/'),
        ),
    ]
