# Generated by Django 5.1 on 2024-09-06 20:05

import django.db.models.deletion
import eLearning_api.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning_api', '0010_alter_course_category_alter_course_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(0, 'undefined'), (10, 'Active'), (40, 'Blocked'), (50, 'Archived')], default=eLearning_api.utils.Status['Active']),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='status',
            field=models.IntegerField(choices=[(0, 'undefined'), (10, 'Active'), (40, 'Blocked'), (50, 'Archived')], default=eLearning_api.utils.Status['Active']),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.IntegerField(choices=[(0, 'undefined'), (10, 'Active'), (40, 'Blocked'), (50, 'Archived')], default=eLearning_api.utils.Status['Active']),
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('user_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'undefined'), (10, 'Active'), (40, 'Blocked'), (50, 'Archived')], default=eLearning_api.utils.Status['Active'])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='eLearning_api.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursecreator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
