# Generated by Django 5.1 on 2024-09-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearning_api', '0013_coursefeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
